baseURL = "https://polo123456789.github.io/"
languageCode = "en-us"
title = "Guias"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Pablo Sanchez"
    description = "Guias de programacion"
    githubUsername = "Polo123456789"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/cpp/"
    name = "C++"
    weight = 3

[[menu.icon]]
    url = "mailto:pabsan.dev@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Polo123456789/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://es.stackoverflow.com/users/153685/pablochaches"
    name = "fab fa-stack-overflow"
    weight = 3
